name: Build Paper Plugin

on:
  push:
    paths:
      - 'paperlink-server/**'
      - '.github/workflows/build-paper.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: paperlink-server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Jar
      run: ./gradlew build

    - name: Upload Paper Plugin
      uses: actions/upload-artifact@v4
      with:
        name: paperlink-server
        path: paperlink-server/build/libs/*.jar
